### ISSUE TITLE
tf_exchange

### ISSUE THREAD

**Issue by Adrian-Sam** [msminirobot/ROS2swarm#21]
Hi
I followed the steps as described in installation guide, when trying to launch the start_simulation.sh script I'm running into the error:

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/packages.py", line 50, in get_package_prefix
    content, package_prefix = get_resource('packages', package_name)
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/resources.py", line 48, in get_resource
    raise LookupError(
LookupError: Could not find the resource 'tf_exchange' of type 'packages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 53, in get_launch_description_from_any_launch_file
    return loader(launch_file_path)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/python_launch_file_utilities.py", line 68, in get_launch_description_from_python_launch_file
    return getattr(launch_file_module, 'generate_launch_description')()
  File "/home/rosvm/ROS2swarm/install/launch_gazebo/share/launch_gazebo/create_enviroment.launch.py", line 38, in generate_launch_description
    tf_exchange_dir = get_package_share_directory('tf_exchange')
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/packages.py", line 70, in get_package_share_directory
    return os.path.join(get_package_prefix(package_name), 'share', package_name)
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/packages.py", line 52, in get_package_prefix
    raise PackageNotFoundError(
ament_index_python.packages.PackageNotFoundError: "package 'tf_exchange' not found, searching: ['/home/rosvm/ROS2swarm/install/ros2swarm', '/home/rosvm/ROS2swarm/install/launch_gazebo', '/home/rosvm/ROS2swarm/install/communication_interfaces', '/home/rosvm/turtlebot3_ws/install/turtlebot3', '/home/rosvm/turtlebot3_ws/install/turtlebot3_teleop', '/home/rosvm/turtlebot3_ws/install/turtlebot3_simulations', '/home/rosvm/turtlebot3_ws/install/turtlebot3_bringup', '/home/rosvm/turtlebot3_ws/install/turtlebot3_node', '/home/rosvm/turtlebot3_ws/install/turtlebot3_navigation2', '/home/rosvm/turtlebot3_ws/install/turtlebot3_fake_node', '/home/rosvm/turtlebot3_ws/install/turtlebot3_example', '/home/rosvm/turtlebot3_ws/install/turtlebot3_msgs', '/home/rosvm/turtlebot3_ws/install/turtlebot3_gazebo', '/home/rosvm/turtlebot3_ws/install/turtlebot3_description', '/home/rosvm/turtlebot3_ws/install/turtlebot3_cartographer', '/opt/ros/foxy']"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/include_launch_description.py", line 130, in execute
    launch_description = self.__launch_description_source.get_launch_description(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_source.py", line 84, in get_launch_description
    self._get_launch_description(self.__expanded_location)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_description_source.py", line 53, in _get_launch_description
    return get_launch_description_from_any_launch_file(location)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 56, in get_launch_description_from_any_launch_file
    raise InvalidLaunchFileError(extension, likely_errors=exceptions)
launch.invalid_launch_file_error.InvalidLaunchFileError: Caught exception when trying to load file of format [py]: "package 'tf_exchange' not found, searching: ['/home/rosvm/ROS2swarm/install/ros2swarm', '/home/rosvm/ROS2swarm/install/launch_gazebo', '/home/rosvm/ROS2swarm/install/communication_interfaces', '/home/rosvm/turtlebot3_ws/install/turtlebot3', '/home/rosvm/turtlebot3_ws/install/turtlebot3_teleop', '/home/rosvm/turtlebot3_ws/install/turtlebot3_simulations', '/home/rosvm/turtlebot3_ws/install/turtlebot3_bringup', '/home/rosvm/turtlebot3_ws/install/turtlebot3_node', '/home/rosvm/turtlebot3_ws/install/turtlebot3_navigation2', '/home/rosvm/turtlebot3_ws/install/turtlebot3_fake_node', '/home/rosvm/turtlebot3_ws/install/turtlebot3_example', '/home/rosvm/turtlebot3_ws/install/turtlebot3_msgs', '/home/rosvm/turtlebot3_ws/install/turtlebot3_gazebo', '/home/rosvm/turtlebot3_ws/install/turtlebot3_description', '/home/rosvm/turtlebot3_ws/install/turtlebot3_cartographer', '/opt/ros/foxy']"
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

apparently the issue is raised to a missing (tf_exchange) package.
I tried searching for such package but couldn't find any.
Is this right or am I getting something wrong? I'm still novice with ROS

**Comment by PioneerAIRobots** [comment]
same problem with me, tf_exchange package not found.

**Comment by Adrian-Sam** [comment]
sorry didn't notice it was solved in "Closed"
